config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get "home/about" => "homes#about"

  devise_for :users
  resources :users, only: [:index,:show,:edit,:update]

  resources :books, only: [:create, :index, :show, :destroy, :edit, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
  resources :relationships, only: [:create, :destroy] 
   get "relationship/follow_users" => "relationships#follow_users"
   get "relationship/follower_users" => "relationships#follower_users"
   
  get "/search" => "searches#search"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  #book,いいね,コメントのアソシエーション
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  # フォロー機能部分のアソシエーション
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "follow_id"
  has_many :followers, through: :reverse_of_relationships, source: :user

  #フォロー機能のメソッド
  #自分とフォロー先が一緒じゃないか検証
  def follow(other_user)
    unless self == other_user
    self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end
  # 既存のフォロワーならフォロー解除する
  def unfollow(other_user)
    relationships = self.relationships.find_by(follow_id: other_user.id)
    relationships.destroy if relationships
  end
  #フォロワーの中に含まれてない？
  def following?(other_user)
    self.followings.include?(other_user)
  end

  #プロフィール画像のattachment
  attachment :profile_image

  #validation
  validates :name, length: {in: 2..20}, uniqueness: { case_sensitive: false }
  validates :introduction ,length: {maximum: 50}

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def index
    @following = User.new
    @user = current_user
    @users = User.all
    @book = Book.new
  end

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice] = "You have updated user successfully."
       redirect_to user_path(@user.id)
    else
       render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:profile_image, :name, :introduction)
  end

  def correct_user
      @user = User.find(params[:id])
      redirect_to user_path(current_user) unless @user == current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_info.html.erb
<script src="https://kit.fontawesome.com/f03fd448b3.js" crossorigin="anonymous"></script>

<!--ログインしているユーザー情報-->
 <h2>User info</h2>
    <%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size:'80x80' %>
  <table class="table">
    <tbody>

      <tr>
	      <th>name</th>
	      <th><%= user.name %></th>
      </tr>

      <tr>
	      <th>introduction</th>
	      <th><%= user.introduction %></th>
      </tr>

      <tr>
        <!--フォロー・フォロワー欄　クリックするとエラーになる-->
        <th>follows</th>
        <th><%= link_to user.followings.count, relationship_follow_users_path(follow_id: user.id) %></th>
      </tr>
      <tr>
        <th>followers</th>
        <th><%= link_to user.followers.count, relationship_follower_users_path(follow_id: user.id) %></th>
      </tr>

    </tbody>
  </table>
  <div class="row">
    <% if user == current_user %>
      <%= link_to "", edit_user_path(user) , class:"btn btn-outline-secondary btn-block fas fa-user-cog"%>
    <% end %>
  </div>

app/views/users/_users_search.html.erb
<main>
<table>
    <thead>
        <tr>
            <th>image</th>
            <th>name</th>
            <th>introduction</th>
        </tr>
    </thead>
    <tbody id ="user">
        <% users.each do |user| %>
        <tr>
            <td>
            <%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size:'40x50' %>
            </td>
            <td><%= link_to user_path(user) do %>
                <%= user.name %>
                <% end %>
            </td>
            <td><%= user.introduction %></td>
        </tr>
        <% end %>
    </tbody>
</table>
</main>

app/views/users/_users_serch.html.erb
<table>
    <thead>
        <tr>
            <th>image</th>
            <th>name</th>
            <th>introduction</th>
        </tr>
    </thead>
    <tbody id ="user">
        <% users.each do |user| %>
        <tr>
            <td>
            <%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size:'40x50' %>
            </td>
            <td><%= link_to user_path(user) do %> <!--book.user.idから変更-->
                <%= user.name %>
                <% end %>
            </td>
            <td><%= user.introduction %></td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/users/edit.html.erb
 


<main>
 
   <% if @user.errors.any? %>
   <div class = "text-danger h2">
    <%= @user.errors.count %> errors prohibited this obj from being saved:
  </div>
    <li class = "text-danger ">
    <% @user.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>
  </li>
  
  <div class="container">
    <div class="row">
     <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>

     <%= form_with model: @user, local:true do |f| %>

      <label for="user_name">Name</label>
       <%= f.text_field :name, class: "form-control name" %>

       <label for="user_image">Image</label>
       <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>

       <label for="user_introduction">Introduction</label>
       <%= f.text_area :introduction ,class: "form-control introduction" %>

        <%= f.submit "Update User", class: "btn btn-secondary bg-secondary text-white" %>

      <% end %>
      </div>
     </div>
  </div>
</main>

app/views/users/index.html.erb
<script src="https://kit.fontawesome.com/f03fd448b3.js" crossorigin="anonymous"></script>
<p id="notice"></p>
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <%= render "users/info", user: @user %> <!--ログイン者情報-->
        <%= render 'books/new', book: @book %> <!--投稿情報-->
      </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
          <tbody>
             <% @users.each do |user| %>
            <tr>
                <td><%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size:'40x50'%></td>
                <td><%= user.name %></td>

                <!--フォローフォロワー機能-->

                <td>
                  <p>フォロー数：<%= user.followings.count %></p>
                </td>
                 <td>
                  <p>フォロワー数：<%= user.followings.count %></p>
                </td>
                <td>
                  <% unless current_user == user %>

                   <% if current_user.following?(user) %>
                     <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
                       <%= hidden_field_tag :follow_id, user.id %>
                       <%= f.submit 'フォローを外す', class: 'btn btn-secondary  bg-info text-white' %>
                     <% end %>

                   <% else %>

                     <%= form_for(current_user.relationships.build) do |f| %>
                       <%= hidden_field_tag :follow_id, user.id %>
                       <%= f.submit 'フォローする', class: 'btn btn-secondary  bg-success text-white' %>
                     <% end %>
                   <% end %>

                  <% end %>
                </td>

                <td><%= link_to "Show", user_path(user) %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<script src="https://kit.fontawesome.com/f03fd448b3.js" crossorigin="anonymous"></script>

<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <%= render "users/info", user: @user %>
        <%= render "relationships/follow", user: @user %>
        <%= render 'books/new', book: @book %>
      </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table">
        <thead>
          <tr>
            <th>title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
          <tbody>
             <% @books.each do |book| %>
            <tr>
                <td><%= link_to user_path(book.user.id) do %>
                  <%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", size:'40x50' %>
                  <% end %></td>
                <td><%= link_to book.title, book_path(book) %></td>
                <td><%= book.body %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</main>