config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get "home/about" => "homes#about"

  devise_for :users
  resources :users, only: [:index,:show,:edit,:update]

  resources :books, only: [:create, :index, :show, :destroy, :edit, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
  resources :relationships, only: [:create, :destroy] 
   get "relationship/follow_users" => "relationships#follow_users"
   get "relationship/follower_users" => "relationships#follower_users"
   
  get "/search" => "searches#search"

end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
   before_action :authenticate_user!
   before_action :correct_user, only: [:edit, :update]

  def create
    @book = Book.new(book_params)
    @book.user = current_user
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def index
   @books = Book.all
   @user = current_user
   @book = Book.new
  end

  def show
    @book = Book.new
    @book_comment = BookComment.new
    @book_detail = Book.find(params[:id])
    @user = current_user
  end

  def edit
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def update
    @book =Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path
    else
      @user = current_user
      @book_detail = Book.find(params[:id])
      render :edit
    end
  end

   def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
   end




  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_books_search.html.erb
<main>
 <table class = table>
    <thead>
        <tr>
            <th>Image</th>
            <th>Title</th>
            <th>Opinion</th>
        </tr>
    </thead>
    <tbody>
        <% books.each do |book| %>
         <tr>
            <td><%= link_to user_path(book.user.id) do %>
              <%= attachment_image_tag book.user, :profile_image, fallback: "no_image.jpg", size:'40x40' %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book) %></td>
            <td><%= book.body %></td>
         </tr>
        <% end %>
    </tbody>
</table>
</main>

app/views/books/_books_serch.html.erb
<table>
    <thead>
        <tr>
            <th>Image</th>
            <th>Title</th>
            <th>Opinion</th>
        </tr>
    </thead>
    <tbody>
        <%= books.each do |book| %>
         <tr>
            <td><%#= link_to user_path(book.user.id) do %>
              <%= attachment_image_tag book.user, :profile_image, fallback: "no_image.jpg", size:'40x40' %>
              <%# end %>
            </td>
            <td><%= link_to book.title, book_path(book) %></td>
            <td><%= book.body %></td>
         </tr>
    </tbody>
</table>

app/views/books/_new.html.erb
 


  <!--新規投稿フォーム-->
  <h2 class="mt-3">New book</h2>
    <%= form_with model: book, local:true do |f| %>
      <div class="form-group">
        <label for="book_title">Title</label>
        <%= f.text_field :title, class:"form-control book_title" %>
      </div>
      <div class="form-group">
        <label for="book_opinion">Opinion</label>
        <%= f.text_area :body, class:"form-control book_opinion" %>
      </div>

        <%= f.submit 'Create Book', class:"btn btn-secondary  bg-success text-white" %>

    <% end %>

app/views/books/edit.html.erb
<main>
  
  <% if @book.errors.any? %>
  <div class = "text-danger h2">
    <%= @book.errors.count %> errors prohibited this obj from being saved:
  </div>
  <div>
    <li class = "text-danger">
    <% @book.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
    </li>
  <% end %>
  </div>

  <%= flash[:notice] %>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  	  	<h1>Editing Book</h1>
      	<%= form_with model: @book, local:true do |f| %>
          <label for="book_title">Title</label>
            <%= f.text_field :title , class: "form-control" %>
          <label for="book_opinion">Opinion</label>
            <%= f.text_area :body, class: "form-control" %>
            <%= f.submit 'Update Book', class: "btn btn-secondary bg-success text-white" %>
          <% end %>

  		<%= link_to "Show",book_path(@book) %>
  		 | 
  		<%= link_to "Back",books_path %>

    </div>
  </div>
</main>

app/views/books/index.html.erb
<script src="https://kit.fontawesome.com/f03fd448b3.js" crossorigin="anonymous"></script>
<p id="notice"></p>
<main>

   <% if @book.errors.any? %>
     <div class = "text-danger h2">
      <%= @book.errors.count %> errors prohibited this obj from being saved:
      </div>
    <li class = "text-danger">
        <% @book.errors.full_messages.each do |message| %>
        <%= message %>
        <% end %>
    <% end %>
    </li>

  <div class="container px-5 px-sm-0">
    <div class = "row">
      <div class="col-md-3">
       <%= render "users/info", user: @user %>
       <%= render 'books/new', book: @book %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <!--bookの投稿一覧-->
        <% @books.each do |book| %>
          <tr>

            <td><%= link_to user_path(book.user.id) do %>
              <%= attachment_image_tag book.user, :profile_image, fallback: "no_image.jpg", size:'40x40' %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book) %></td>
            <td><%= book.body %></td>

          <!--いいね機能-->

          <td>
            <% if book.favorited_by?(current_user) %>
              <p>
                <%= link_to book_favorites_path(book), method: :DELETE do %>
                <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
                 ♥<%= book.favorites.count %> いいね
                <% end %>
              </p>
            <% else %>
              <p>
                <%= link_to book_favorites_path(book), method: :POST do %>
                 <i class="fa fa-heart-o" aria-hidden="true"></i>
                  ♡<%= book.favorites.count %> いいね
                <% end %>
              </p>
           <% end %>
          </td>
          <td>
            <p>コメント数：<%= book.book_comments.count %></p>
          </td>
         <% end %>
        </tr>
        </tbody>
      </table>
      </div>
    </div>
  </div>
</main>

app/views/books/show.html.erb
<script src="https://kit.fontawesome.com/f03fd448b3.js" crossorigin="anonymous"></script>
<p id="notice"></p>
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <%= render 'users/info', user: @book_detail.user %>
        <%= render 'books/new', book: @book %>
      </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
           <td>
             <%= attachment_image_tag @book_detail.user, :profile_image,fallback: "no_image.jpg", size:'40x40' %><br>
             <%= link_to @book_detail.user.name, user_path(@book_detail.user.id) %>
             </td>
           <td><%= link_to @book_detail.title, book_path %></td>
           <td><%= @book_detail.body %></td>

          <!--いいね機能-->
          <td>
            <% if @book.favorited_by?(current_user) %>
              <p>
                <%= link_to book_favorites_path(@book), method: :DELETE do %>
                <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
                 ♥<%= @book.favorites.count %> いいね
                <% end %>
              </p>
            <% else %>
              <p>
                <%= link_to book_favorites_path(@book_detail), method: :POST do %>
                 <i class="fa fa-heart-o" aria-hidden="true"></i>
                  ♡<%= @book.favorites.count %> いいね
                <% end %>
              </p>
           <% end %>
          </td>
           <td>
             <% if @book_detail.user == current_user %>
              <%= link_to "Edit", edit_book_path(@book_detail), class: "btn btn-sm btn-secondary bg-success text-white"%>
             <% end %>
          </td>
          <td>
              <% if @book_detail.user == current_user %>
                <%= link_to "Destroy", book_path(@book_detail), method: :delete,class: "btn btn-sm btn-secondary bg-danger text-white" ,"data-confirm" => "本当に削除しますか？"%>
              <% end %>
          </td>
          <td>
            <p>コメント数：<%= @book_detail.book_comments.count %></p>
          </td>
        </tr>

          <!--コメント機能-->
          <tbody>
        
            <% @book_detail.book_comments.each do |book_comment|%>
            <tr>
             <td>
              <%= attachment_image_tag book_comment.user, :profile_image,fallback: "no_image.jpg", size:'40x40' %><br>
              <%= link_to book_comment.user.name, user_path(@book_detail.user.id) %>
             </td>
             <td>
             <%= book_comment.comment %>
             </td>
             <td>
             <% if book_comment.user == current_user %>
                  <%= link_to "Destroy",  book_book_comment_path(book_comment.book,book_comment), method: :delete,class: "btn btn-sm btn-secondary bg-danger text-white" %>
                <% end %>
            </td>
            </tr>
            <% end %>
          
          <tr>
          <td>
            <%= form_with(model:[@book_detail, @book_comment], local: true) do |f| %>
            <div class="form-group">
              <%=f.text_area:comment,rows:"5" ,class:"form-control" %>
            </div>
              <%= f.submit "送信" %>
            <% end %>
          </td>
          </tr>
          </tbody>
        </tbody>
      </table>
    </div>
  </div>
</main>