config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get "home/about" => "homes#about"

  devise_for :users
  resources :users, only: [:index,:show,:edit,:update]

  resources :books, only: [:create, :index, :show, :destroy, :edit, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
  resources :relationships, only: [:create, :destroy] 
   get "relationship/follow_users" => "relationships#follow_users"
   get "relationship/follower_users" => "relationships#follower_users"
   
  get "/search" => "searches#search"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :book
  belongs_to :user
  
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: "User"

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  #book,いいね,コメントのアソシエーション
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  # フォロー機能部分のアソシエーション
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "follow_id"
  has_many :followers, through: :reverse_of_relationships, source: :user

  #フォロー機能のメソッド
  #自分とフォロー先が一緒じゃないか検証
  def follow(other_user)
    unless self == other_user
    self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end
  # 既存のフォロワーならフォロー解除する
  def unfollow(other_user)
    relationships = self.relationships.find_by(follow_id: other_user.id)
    relationships.destroy if relationships
  end
  #フォロワーの中に含まれてない？
  def following?(other_user)
    self.followings.include?(other_user)
  end

  #プロフィール画像のattachment
  attachment :profile_image

  #validation
  validates :name, length: {in: 2..20}, uniqueness: { case_sensitive: false }
  validates :introduction ,length: {maximum: 50}

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
   before_action :authenticate_user!
   before_action :correct_user, only: [:edit, :update]

  def create
    @book = Book.new(book_params)
    @book.user = current_user
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def index
   @books = Book.all
   @user = current_user
   @book = Book.new
  end

  def show
    @book = Book.new
    @book_comment = BookComment.new
    @book_detail = Book.find(params[:id])
    @user = current_user
  end

  def edit
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def update
    @book =Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path
    else
      @user = current_user
      @book_detail = Book.find(params[:id])
      render :edit
    end
  end

   def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
   end




  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.new(book_id: @book.id)
    @favorite.save
    redirect_to request.referer
  end

  def destroy
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.find_by(book_id: @book.id)
    @favorite.destroy
    redirect_to request.referer
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def top 
    end
    
    def about
    end


end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
    def search
        @model = params["model"] #選択したモデル
        @method = params["method"] #検索方法
        @content = params["content"] #検索ワード
        @records = search_for(@model,@content,@method) #上記③つを代入
    end
    
    private
  
    def search_for(model, content, method)
      
      if model == "user" #選択したモデルがUserだった場合
        if method == "perfect" #完全一致なら
          User.where(name: content)
        elsif method == "forward"  #前方一致なら
          User.where("name LIKE?","#{content}%")
        elsif method == "backward" #後方一致なら
          User.where("name LIKE?","%#{content}")
        elsif method == "partial" #部分一致なら
          User.where("name LIKE ?", "%"+content+"%")
        else
          User.all
        end
        
      elsif model == "book" #選択したモデルがBookの場合
      
        if method == "perfect" #完全一致なら
         Book.where(title: content)
        elsif method == "forward"  #前方一致なら
          Book.where("title LIKE?","#{content}%")
        elsif method == "backward" #後方一致なら
          Book.where("title LIKE?","%#{content}")
        elsif method == "partial" #部分一致なら
          Book.where("title LIKE ?", "%"+content+"%")
        else 
          Book.all
        end
        
      end
    end
      
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def index
    @following = User.new
    @user = current_user
    @users = User.all
    @book = Book.new
  end

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice] = "You have updated user successfully."
       redirect_to user_path(@user.id)
    else
       render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:profile_image, :name, :introduction)
  end

  def correct_user
      @user = User.find(params[:id])
      redirect_to user_path(current_user) unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/serches_helper.rb
module SerchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_notifications.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "flash flash__#{key} test-success") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!--javascriptを読み込むタグ-->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/f03fd448b3.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
   <body>
     
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          
          <div class="container">
            <a class="navbar-brand" href="/"><span>Bookers</span></a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="true" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              
              <%= render "searches/searchform" %> <!--検索-->
              
            <div class="navbar-collapse collapse show" id="navbarNavDropdown" style="">
              <ul class="navbar-nav ml-auto">
                
              <% if user_signed_in? %>
                  <li class="fas fa-home nav-link text-light">
                <%= link_to "Home", user_path(current_user), class:"text-white" %>
                  </li>
                  <li class="fas fa-users nav-link text-light">
                <%= link_to "Users", users_path, class:"text-white"%>
                  </li>
                  <li class="fas fa-book-open nav-link text-light">
                    <%= link_to "Books", books_path, class:"text-white" %>
                  </li>
                  <li class="fas fa-sign-out-alt nav-link text-light">
                    <%= link_to "logout", destroy_user_session_path, method: :delete, class:"text-white" %>
                  </li>

              <% else %>

                  <li class="fas fa-home nav-link text-light">
                    <%= link_to "Home", root_path, class:"text-white" %>
                  </li>
                  <li class="fas fa-link  nav-link text-light">
                    <%= link_to "About", home_about_path, class:"text-white" %>
                  </li>
                  <li class="fas fa-user-plus nav-link text-light">
                    <%= link_to "sign up", new_user_registration_path, class:"text-white" %>
                  </li>
                  <li class="fas fa-sign-in-alt nav-link text-light">
                    <%= link_to "login", new_user_session_path, class:"text-white" %>
                  </li>
              <% end %>
              </ul>
            </div>
          </div>
        </nav>
    </header>

    <main>
      
    <p id="notice"></p
    <%= render 'layouts/notifications' %>
    
    <%= yield %>
    

    
    </main>

    <footer>
      <div class="container mt-5">
  	    <div class="row">
    	    <div class="mx-auto">
    		    <p>CopyRight Infratop.inc</p>
    	     </div>
        </div>
      </div>
    </footer>

  </body>
</html>